{"uuid": "1b550b2b-ad7e-40e2-97ba-602613aedb38", "children": ["088a0170-a122-49ce-add0-f9a489069869"], "befores": [{"name": "Фикстура создания задачи", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка при создании задачи\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code\n", "trace": "  File \"/Users/iliakarpenko/Dev/test_exam/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/iliakarpenko/Dev/test_exam/venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/iliakarpenko/Dev/test_exam/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/iliakarpenko/Dev/test_exam/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/iliakarpenko/Dev/test_exam/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/iliakarpenko/Dev/test_exam/tests/conftest.py\", line 91, in task_fixture_only_create\n    assert create_response.status_code == 200,(\n        \"Ошибка при создании задачи\")\n"}, "steps": [{"name": "Создание задачи через API", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка при создании задачи\nassert 404 == 200\n +  where 404 = <Response [404]>.status_code\n", "trace": "  File \"/Users/iliakarpenko/Dev/test_exam/tests/conftest.py\", line 91, in task_fixture_only_create\n    assert create_response.status_code == 200,(\n        \"Ошибка при создании задачи\")\n"}, "start": 1744648567068, "stop": 1744648567321}], "start": 1744648567068, "stop": 1744648567322}], "start": 1744648567068, "stop": 1744648567333}